
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;

public class AnaEkran extends javax.swing.JFrame {  // Tüm pencere güncellemelerinin gerçekleştiği Jframe

    public Karsilama karsilama = new Karsilama();   // giriş introsu
    public Login login = new Login();               // login ekranı

    public AnaEkran() {
        Main.ekranX = (int) Main.kit.getScreenSize().width;     // kullanıcının Ekran boyutunun genişliğini alıyoruz...
        Main.ekranY = (int) Main.kit.getScreenSize().height;    // kullanıcının Ekran boyutunun yüksekliğini alıyoruz...          
        this.setVisible(true);
        this.setResizable(true);
        this.setSize(800, 600);
        this.add(karsilama);
        this.setLocation((Main.ekranX - 800) / 2, (Main.ekranY - 600) / 2);

        karsilama.setVisible(true);
        try {
            Thread.sleep(2500);
        } catch (InterruptedException ex) {
            Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
        karsilama.setVisible(false);

        this.add(login);
        login.setVisible(true);

        this.setTitle("MTFLİX");
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {    // kullanıcı programı kapatınca veri tabanı bağlantıları kapatılır.
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    Main.baglanti.close();
                } catch (SQLException ex) {
                    Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    Main.statement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
