
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
     Register register;            
    public Login() {
        initComponents();
        this.setBackground(Color.BLACK );        
        okIcon.setVisible(false);
         parola.setEchoChar((char)0);
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwdIcon = new javax.swing.JLabel();
        okIcon = new javax.swing.JLabel();
        netflixLogosu = new javax.swing.JLabel();
        eposta = new javax.swing.JTextField();
        mailIcon = new javax.swing.JLabel();
        parola = new javax.swing.JPasswordField();
        kaydol = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        pwdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parola.jpg"))); // NOI18N
        add(pwdIcon);
        pwdIcon.setBounds(470, 380, 30, 30);

        okIcon.setBackground(new java.awt.Color(0, 0, 0));
        okIcon.setForeground(new java.awt.Color(255, 255, 255));
        okIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.jpg"))); // NOI18N
        add(okIcon);
        okIcon.setBounds(470, 380, 20, 30);

        netflixLogosu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        add(netflixLogosu);
        netflixLogosu.setBounds(280, 50, 220, 220);

        eposta.setBackground(new java.awt.Color(0, 0, 0));
        eposta.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        eposta.setForeground(new java.awt.Color(255, 255, 255));
        eposta.setText("E-posta");
        eposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epostaMouseClicked(evt);
            }
        });
        add(eposta);
        eposta.setBounds(290, 330, 170, 30);

        mailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.jpg"))); // NOI18N
        add(mailIcon);
        mailIcon.setBounds(470, 330, 30, 30);

        parola.setBackground(new java.awt.Color(0, 0, 0));
        parola.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        parola.setForeground(new java.awt.Color(255, 255, 255));
        parola.setText("Parola");
        parola.setPreferredSize(new java.awt.Dimension(79, 23));
        parola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parolaMouseClicked(evt);
            }
        });
        add(parola);
        parola.setBounds(290, 380, 170, 30);

        kaydol.setBackground(new java.awt.Color(0, 0, 0));
        kaydol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kaydol.setForeground(new java.awt.Color(204, 204, 204));
        kaydol.setText("Şimdi Kaydol");
        kaydol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaydolMouseClicked(evt);
            }
        });
        add(kaydol);
        kaydol.setBounds(340, 470, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void epostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epostaMouseClicked
 eposta.setText("");
    }//GEN-LAST:event_epostaMouseClicked

    private void parolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parolaMouseClicked
        parola.setText("");
        pwdIcon.setVisible(false);
        okIcon.setVisible(true);
     parola.setEchoChar('*');
    }//GEN-LAST:event_parolaMouseClicked

    private void kaydolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydolMouseClicked
        // TODO add your handling code here:
        register =new Register();            
        this.setVisible(true);
        this.setSize(800,600);
        Main.ekran.add(register);
        Main.ekran.login.setVisible(false);
    }//GEN-LAST:event_kaydolMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eposta;
    private javax.swing.JLabel kaydol;
    private javax.swing.JLabel mailIcon;
    private javax.swing.JLabel netflixLogosu;
    private javax.swing.JLabel okIcon;
    private javax.swing.JPasswordField parola;
    private javax.swing.JLabel pwdIcon;
    // End of variables declaration//GEN-END:variables
}
