
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        this.setBackground(Color.BLACK );
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eposta = new javax.swing.JTextField();
        mailIcon = new javax.swing.JLabel();
        pwdIcon = new javax.swing.JLabel();
        parolaOnay = new javax.swing.JPasswordField();
        okIcon = new javax.swing.JLabel();
        bday = new javax.swing.JTextField();
        bdayIcon = new javax.swing.JLabel();
        isim = new javax.swing.JTextField();
        kisilerIcon = new javax.swing.JLabel();
        netflixLogosu = new javax.swing.JLabel();
        parola = new javax.swing.JPasswordField();
        pwdIcon1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        eposta.setBackground(new java.awt.Color(0, 0, 0));
        eposta.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        eposta.setForeground(new java.awt.Color(255, 255, 255));
        eposta.setText("E-posta");
        eposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epostaMouseClicked(evt);
            }
        });
        add(eposta);
        eposta.setBounds(290, 390, 170, 30);

        mailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.jpg"))); // NOI18N
        add(mailIcon);
        mailIcon.setBounds(470, 390, 30, 30);

        pwdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parola.jpg"))); // NOI18N
        add(pwdIcon);
        pwdIcon.setBounds(470, 490, 30, 30);

        parolaOnay.setBackground(new java.awt.Color(0, 0, 0));
        parolaOnay.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        parolaOnay.setForeground(new java.awt.Color(255, 255, 255));
        parolaOnay.setText("*********");
        parolaOnay.setPreferredSize(new java.awt.Dimension(79, 23));
        parolaOnay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parolaOnayMouseClicked(evt);
            }
        });
        add(parolaOnay);
        parolaOnay.setBounds(290, 490, 170, 30);

        okIcon.setBackground(new java.awt.Color(0, 0, 0));
        okIcon.setForeground(new java.awt.Color(255, 255, 255));
        okIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.jpg"))); // NOI18N
        add(okIcon);
        okIcon.setBounds(470, 490, 20, 30);

        bday.setBackground(new java.awt.Color(0, 0, 0));
        bday.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        bday.setForeground(new java.awt.Color(255, 255, 255));
        bday.setText("Doğum Tarihi");
        bday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bdayMouseClicked(evt);
            }
        });
        add(bday);
        bday.setBounds(290, 340, 170, 30);

        bdayIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bday.jpg"))); // NOI18N
        add(bdayIcon);
        bdayIcon.setBounds(470, 340, 30, 30);

        isim.setBackground(new java.awt.Color(0, 0, 0));
        isim.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        isim.setForeground(new java.awt.Color(255, 255, 255));
        isim.setText("Ad-Soyad");
        isim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isimMouseClicked(evt);
            }
        });
        add(isim);
        isim.setBounds(290, 290, 170, 30);

        kisilerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kisiler.jpg"))); // NOI18N
        add(kisilerIcon);
        kisilerIcon.setBounds(470, 290, 30, 30);

        netflixLogosu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        add(netflixLogosu);
        netflixLogosu.setBounds(280, 50, 220, 220);

        parola.setBackground(new java.awt.Color(0, 0, 0));
        parola.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        parola.setForeground(new java.awt.Color(255, 255, 255));
        parola.setText("Parolddda");
        parola.setPreferredSize(new java.awt.Dimension(79, 23));
        parola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parolaMouseClicked(evt);
            }
        });
        add(parola);
        parola.setBounds(290, 440, 170, 30);

        pwdIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parola.jpg"))); // NOI18N
        add(pwdIcon1);
        pwdIcon1.setBounds(470, 440, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void epostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epostaMouseClicked
        
        eposta.setText("");
    }//GEN-LAST:event_epostaMouseClicked

    private void parolaOnayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parolaOnayMouseClicked
        parolaOnay.setText("");
        pwdIcon.setVisible(false);
    }//GEN-LAST:event_parolaOnayMouseClicked

    private void isimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isimMouseClicked
       isim.setText("");
    }//GEN-LAST:event_isimMouseClicked

    private void bdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdayMouseClicked
        bday.setText("");
    }//GEN-LAST:event_bdayMouseClicked

    private void parolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parolaMouseClicked
        // TODO add your handling code here:
        parola.setText("");
    }//GEN-LAST:event_parolaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bday;
    private javax.swing.JLabel bdayIcon;
    private javax.swing.JTextField eposta;
    private javax.swing.JTextField isim;
    private javax.swing.JLabel kisilerIcon;
    private javax.swing.JLabel mailIcon;
    private javax.swing.JLabel netflixLogosu;
    private javax.swing.JLabel okIcon;
    private javax.swing.JPasswordField parola;
    private javax.swing.JPasswordField parolaOnay;
    private javax.swing.JLabel pwdIcon;
    private javax.swing.JLabel pwdIcon1;
    // End of variables declaration//GEN-END:variables
}
